FROM jlesage/baseimage-gui:ubuntu-24.04-v4

# 安装必要依赖
RUN apt update && \
    apt install -y fonts-noto-cjk-extra curl \
    shared-mime-info desktop-file-utils libxcb1 libxcb-icccm4 libxcb-image0 \
    libxcb-keysyms1 libxcb-randr0 libxcb-render0 libxcb-render-util0 libxcb-shape0 \
    libxcb-shm0 libxcb-sync1 libxcb-util1 libxcb-xfixes0 libxcb-xkb1 libxcb-xinerama0 \
    libxcb-xkb1 libxcb-glx0 libatk1.0-0t64 libatk-bridge2.0-0t64 libc6 libcairo2 libcups2t64 \
    libdbus-1-3 libfontconfig1 libgbm1 libgcc1 libgdk-pixbuf2.0-0 libglib2.0-0t64 \
    libgtk-3-0t64 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 \
    libxcomposite1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 \
    libxss1 libxtst6 libatomic1 libxcomposite1 libxrender1 libxrandr2 libxkbcommon-x11-0 \
    libfontconfig1 libdbus-1-3 libnss3 libx11-xcb1 libasound2t64 libtiff-dev wget

RUN wget -O libjpeg-turbo.deb http://ftp.br.debian.org/debian/pool/main/libj/libjpeg-turbo/libjpeg62-turbo_2.1.5-3+b1_arm64.deb && dpkg -i libjpeg-turbo.deb

RUN wget -O libtiff5.deb https://security.debian.org/pool/updates/main/t/tiff/libtiff5_4.2.0-1+deb11u5_arm64.deb && wget -O libwebp6.deb https://security.debian.org/pool/updates/main/libw/libwebp/libwebp6_0.6.1-2.1+deb11u2_arm64.deb && dpkg -i libtiff5.deb libwebp6.deb

# 清理工作
RUN apt clean && rm -rf /var/lib/apt/lists/*

# 生成微信图标
RUN APP_ICON_URL=https://res.wx.qq.com/a/wx_fed/assets/res/NTI4MWU5.ico && \
    install_app_icon.sh "$APP_ICON_URL"

# 设置应用名称
RUN set-cont-env APP_NAME "Wechat"
